/* Generated by ROX profile/configuration tools. Public browser configuration only. */
window.ROX_RUNTIME_CONFIG = Object.freeze({
  PROFILE: 'production',
  SUPABASE_URL: 'https://tqoqsgaymygmqrzddvtu.supabase.co',
  SUPABASE_ANON_KEY: 'sb_publishable_jxn-4TT28_G7LtZG4FJXTQ_75JiaSBi',
  API_BASE: 'https://rox-ai-production.up.railway.app',
  FEATURES: Object.freeze({
    projects: true,
    history: true,
    automations: true,
    roxip: true
  })
});