-- ZUVYR - private conversation attachment storage.
-- Apply after 19_history_pinned_order.sql.
-- The bucket accepts MIME types only after server-side validation.
-- Uploaded files remain private and are never executed by ZUVYR.

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'conversation-files',
  'conversation-files',
  false,
  629145600,
  null
)
on conflict (id) do update
set
  name = excluded.name,
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

alter table public.conversation_assets
  add column if not exists storage_bucket text,
  add column if not exists file_size_bytes bigint,
  add column if not exists sha256 text,
  add column if not exists scan_status text not null default 'clean',
  add column if not exists extraction_status text not null default 'not_required';

do $migration$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'conversation_assets_file_size_check'
  ) then
    alter table public.conversation_assets
      add constraint conversation_assets_file_size_check
      check (file_size_bytes is null or file_size_bytes >= 0);
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'conversation_assets_scan_status_check'
  ) then
    alter table public.conversation_assets
      add constraint conversation_assets_scan_status_check
      check (
        scan_status in (
          'pending',
          'scanning',
          'clean',
          'rejected',
          'failed'
        )
      );
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'conversation_assets_extraction_status_check'
  ) then
    alter table public.conversation_assets
      add constraint conversation_assets_extraction_status_check
      check (
        extraction_status in (
          'not_required',
          'pending',
          'processing',
          'ready',
          'unsupported',
          'failed'
        )
      );
  end if;
end
$migration$;

create index if not exists idx_conversation_assets_scan_status
  on public.conversation_assets(conversation_id, scan_status, created_at);

create unique index if not exists idx_conversation_assets_storage_location
  on public.conversation_assets(storage_bucket, storage_path);

-- Large readable files are indexed as bounded text chunks. The original
-- private object remains the source of truth; chunks are untrusted user data.
create table if not exists public.conversation_asset_chunks (
  id bigint generated by default as identity primary key,
  asset_id uuid not null references public.conversation_assets(id) on delete cascade,
  conversation_id uuid not null references public.shared_conversations(id) on delete cascade,
  owner_id uuid not null references auth.users(id) on delete cascade,
  chunk_index integer not null,
  char_start bigint not null default 0,
  char_end bigint not null default 0,
  content text not null,
  metadata jsonb not null default '{}'::jsonb,
  search_document tsvector generated always as (
    to_tsvector('simple', coalesce(content, ''))
  ) stored,
  created_at timestamptz not null default now(),
  constraint conversation_asset_chunks_index_check
    check (chunk_index >= 0),
  constraint conversation_asset_chunks_range_check
    check (char_start >= 0 and char_end >= char_start),
  constraint conversation_asset_chunks_content_check
    check (char_length(content) between 1 and 65536),
  constraint conversation_asset_chunks_asset_index_unique
    unique (asset_id, chunk_index)
);

alter table public.conversation_asset_chunks enable row level security;

create index if not exists idx_conversation_asset_chunks_owner_asset
  on public.conversation_asset_chunks(owner_id, asset_id, chunk_index);

create index if not exists idx_conversation_asset_chunks_search
  on public.conversation_asset_chunks using gin(search_document);

create or replace function public.search_conversation_asset_chunks(
  p_owner_id uuid,
  p_asset_ids uuid[],
  p_query text,
  p_limit integer default 8
)
returns table (
  asset_id uuid,
  chunk_index integer,
  content text,
  char_start bigint,
  char_end bigint,
  rank real
)
language sql
stable
security invoker
set search_path = public
as $search$
  with params as (
    select
      nullif(btrim(coalesce(p_query, '')), '') as query_text,
      least(greatest(coalesce(p_limit, 8), 1), 20) as result_limit
  ),
  ranked as (
    select
      c.asset_id,
      c.chunk_index,
      c.content,
      c.char_start,
      c.char_end,
      ts_rank_cd(
        c.search_document,
        websearch_to_tsquery('simple', p.query_text)
      )::real as rank
    from public.conversation_asset_chunks c
    cross join params p
    where c.owner_id = p_owner_id
      and c.asset_id = any(coalesce(p_asset_ids, array[]::uuid[]))
      and p.query_text is not null
      and c.search_document @@ websearch_to_tsquery('simple', p.query_text)
    order by rank desc, c.chunk_index asc
    limit (select result_limit from params)
  ),
  fallback as (
    select
      c.asset_id,
      c.chunk_index,
      c.content,
      c.char_start,
      c.char_end,
      0::real as rank
    from public.conversation_asset_chunks c
    cross join params p
    where c.owner_id = p_owner_id
      and c.asset_id = any(coalesce(p_asset_ids, array[]::uuid[]))
      and not exists (select 1 from ranked)
    order by c.asset_id, c.chunk_index
    limit (select result_limit from params)
  )
  select * from ranked
  union all
  select * from fallback;
$search$;
