-- ZUVYR Pack 01 - cost, usage and allowance foundation
-- Run after 27_stripe_subscription_invoice_settlement.sql.
--
-- This migration is additive and does not activate charging or plan limits.
-- Every mutation RPC requires p_enforcement_enabled=true and is executable
-- only by service_role. Pack 01 ships with enforcement disabled by default.

begin;

alter table public.profiles
  add column if not exists usage_week_started_at timestamptz,
  add column if not exists usage_week_ends_at timestamptz,
  add column if not exists usage_week_units_total integer,
  add column if not exists usage_week_units_used integer not null default 0;

alter table public.profiles
  drop constraint if exists profiles_zuvyr_week_usage_nonnegative;

alter table public.profiles
  add constraint profiles_zuvyr_week_usage_nonnegative
  check (
    (usage_week_units_total is null or usage_week_units_total >= 0)
    and usage_week_units_used >= 0
  );

alter table public.profiles
  drop constraint if exists profiles_zuvyr_week_window_order;

alter table public.profiles
  add constraint profiles_zuvyr_week_window_order
  check (
    usage_week_started_at is null
    or usage_week_ends_at is null
    or usage_week_ends_at > usage_week_started_at
  );

create table if not exists public.zuvyr_usage_records (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete restrict,
  request_id text not null,
  idempotency_key text not null,
  capability text not null,
  provider text not null,
  model_tool text not null,
  pricing_version text not null,
  funding_source text not null,
  reserved_credits integer not null,
  actual_credits integer,
  refunded_credits integer not null default 0,
  estimated_provider_cost_microusd numeric(20, 0) not null,
  actual_provider_cost_microusd numeric(20, 0),
  revenue_microusd numeric(20, 0),
  gross_profit_microusd numeric(20, 0),
  gross_margin_bps integer,
  provider_usage jsonb not null default '{}'::jsonb,
  state text not null default 'reserved',
  five_hour_started_at timestamptz,
  five_hour_ends_at timestamptz,
  weekly_started_at timestamptz,
  weekly_ends_at timestamptz,
  created_at timestamptz not null default now(),
  settled_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint zuvyr_usage_request_unique unique (request_id),
  constraint zuvyr_usage_idempotency_unique unique (idempotency_key),
  constraint zuvyr_usage_funding_source_allowed
    check (funding_source in ('subscription', 'topup')),
  constraint zuvyr_usage_state_allowed
    check (state in ('reserved', 'settled', 'refunded', 'failed')),
  constraint zuvyr_usage_credit_values_valid
    check (
      reserved_credits > 0
      and (actual_credits is null or actual_credits >= 0)
      and refunded_credits >= 0
      and refunded_credits <= reserved_credits
    ),
  constraint zuvyr_usage_money_values_valid
    check (
      estimated_provider_cost_microusd >= 0
      and (
        actual_provider_cost_microusd is null
        or actual_provider_cost_microusd >= 0
      )
      and (revenue_microusd is null or revenue_microusd >= 0)
    ),
  constraint zuvyr_usage_margin_valid
    check (
      gross_margin_bps is null
      or gross_margin_bps between -1000000 and 10000
    )
);

create index if not exists zuvyr_usage_records_user_created_idx
  on public.zuvyr_usage_records (user_id, created_at desc);

create index if not exists zuvyr_usage_records_state_idx
  on public.zuvyr_usage_records (state, created_at);

alter table public.zuvyr_usage_records enable row level security;

revoke all on table public.zuvyr_usage_records
from public, anon, authenticated;

grant select, insert, update on table public.zuvyr_usage_records
to service_role;

grant usage, select on sequence public.zuvyr_usage_records_id_seq
to service_role;

create or replace function public.protect_sensitive_profile_columns()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
begin
  if auth.role() <> 'service_role' then
    new.credits_total := old.credits_total;
    new.credits_used := old.credits_used;
    new.subscription_status := old.subscription_status;
    new.last_reset_date := old.last_reset_date;
    new.is_admin := old.is_admin;
    new.billing_status := old.billing_status;
    new.stripe_customer_id := old.stripe_customer_id;
    new.stripe_subscription_id := old.stripe_subscription_id;
    new.stripe_price_id := old.stripe_price_id;
    new.subscription_current_period_start :=
      old.subscription_current_period_start;
    new.subscription_current_period_end :=
      old.subscription_current_period_end;
    new.subscription_cancel_at_period_end :=
      old.subscription_cancel_at_period_end;
    new.usage_window_started_at := old.usage_window_started_at;
    new.usage_window_ends_at := old.usage_window_ends_at;
    new.usage_units_total := old.usage_units_total;
    new.usage_units_used := old.usage_units_used;
    new.usage_week_started_at := old.usage_week_started_at;
    new.usage_week_ends_at := old.usage_week_ends_at;
    new.usage_week_units_total := old.usage_week_units_total;
    new.usage_week_units_used := old.usage_week_units_used;
    new.topup_credits_balance := old.topup_credits_balance;
    new.billing_updated_at := old.billing_updated_at;
    new.stripe_subscription_event_created_at :=
      old.stripe_subscription_event_created_at;
    new.stripe_subscription_event_id :=
      old.stripe_subscription_event_id;
  end if;

  return new;
end;
$function$;

revoke execute on function public.protect_sensitive_profile_columns()
from public, anon, authenticated;

grant execute on function public.protect_sensitive_profile_columns()
to service_role;

create or replace function public.reserve_zuvyr_usage(
  p_user_id uuid,
  p_request_id text,
  p_idempotency_key text,
  p_capability text,
  p_provider text,
  p_model_tool text,
  p_pricing_version text,
  p_reserved_credits integer,
  p_estimated_provider_cost_microusd numeric,
  p_allow_topup boolean,
  p_enforcement_enabled boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_profile public.profiles%rowtype;
  v_existing public.zuvyr_usage_records%rowtype;
  v_now timestamptz := clock_timestamp();
  v_week_index bigint;
  v_five_remaining integer;
  v_week_remaining integer;
  v_funding_source text;
begin
  if not coalesce(p_enforcement_enabled, false) then
    return jsonb_build_object(
      'success', false,
      'error', 'usage_enforcement_disabled'
    );
  end if;

  if nullif(trim(p_request_id), '') is null
    or nullif(trim(p_idempotency_key), '') is null
    or nullif(trim(p_capability), '') is null
    or nullif(trim(p_provider), '') is null
    or nullif(trim(p_model_tool), '') is null
    or nullif(trim(p_pricing_version), '') is null
    or p_reserved_credits is null
    or p_reserved_credits <= 0
    or p_estimated_provider_cost_microusd is null
    or p_estimated_provider_cost_microusd < 0
  then
    return jsonb_build_object(
      'success', false,
      'error', 'invalid_usage_reservation'
    );
  end if;

  select *
  into v_existing
  from public.zuvyr_usage_records
  where idempotency_key = trim(p_idempotency_key)
  for update;

  if found then
    if v_existing.user_id <> p_user_id
      or v_existing.request_id <> trim(p_request_id)
    then
      return jsonb_build_object(
        'success', false,
        'error', 'idempotency_conflict'
      );
    end if;

    return jsonb_build_object(
      'success', true,
      'replayed', true,
      'usage_record_id', v_existing.id,
      'funding_source', v_existing.funding_source,
      'reserved_credits', v_existing.reserved_credits,
      'state', v_existing.state
    );
  end if;

  select *
  into v_profile
  from public.profiles
  where id = p_user_id
  for update;

  if not found then
    return jsonb_build_object(
      'success', false,
      'error', 'user_not_found'
    );
  end if;

  if v_profile.subscription_status in ('plus', 'pro', 'legend', 'max')
    and v_profile.billing_status in ('active', 'trialing', 'past_due')
    and v_profile.usage_units_total is not null
    and v_profile.usage_week_units_total is not null
    and v_profile.subscription_current_period_start is not null
  then
    if v_profile.usage_window_ends_at is null
      or v_profile.usage_window_ends_at <= v_now
    then
      v_profile.usage_window_started_at := v_now;
      v_profile.usage_window_ends_at := v_now + interval '5 hours';
      v_profile.usage_units_used := 0;
    end if;

    if v_now < v_profile.subscription_current_period_start then
      return jsonb_build_object(
        'success', false,
        'error', 'weekly_anchor_is_in_the_future'
      );
    end if;

    v_week_index := floor(
      extract(
        epoch from (
          v_now - v_profile.subscription_current_period_start
        )
      ) / 604800
    );

    if v_profile.usage_week_started_at is null
      or v_profile.usage_week_started_at <
        v_profile.subscription_current_period_start +
        (v_week_index * interval '7 days')
    then
      v_profile.usage_week_started_at :=
        v_profile.subscription_current_period_start +
        (v_week_index * interval '7 days');
      v_profile.usage_week_ends_at :=
        v_profile.usage_week_started_at + interval '7 days';
      v_profile.usage_week_units_used := 0;
    end if;

    v_five_remaining := greatest(
      0,
      v_profile.usage_units_total - v_profile.usage_units_used
    );
    v_week_remaining := greatest(
      0,
      v_profile.usage_week_units_total -
        v_profile.usage_week_units_used
    );

    if v_five_remaining >= p_reserved_credits
      and v_week_remaining >= p_reserved_credits
    then
      v_funding_source := 'subscription';

      update public.profiles
      set
        usage_window_started_at = v_profile.usage_window_started_at,
        usage_window_ends_at = v_profile.usage_window_ends_at,
        usage_units_used =
          v_profile.usage_units_used + p_reserved_credits,
        usage_week_started_at = v_profile.usage_week_started_at,
        usage_week_ends_at = v_profile.usage_week_ends_at,
        usage_week_units_used =
          v_profile.usage_week_units_used + p_reserved_credits,
        billing_updated_at = now()
      where id = p_user_id;
    end if;
  end if;

  if v_funding_source is null
    and coalesce(p_allow_topup, false)
    and v_profile.topup_credits_balance >= p_reserved_credits
  then
    v_funding_source := 'topup';

    update public.profiles
    set
      topup_credits_balance =
        topup_credits_balance - p_reserved_credits,
      billing_updated_at = now()
    where id = p_user_id;
  end if;

  if v_funding_source is null then
    return jsonb_build_object(
      'success', false,
      'error', case
        when v_profile.subscription_status in (
          'plus', 'pro', 'legend', 'max'
        )
          and v_profile.billing_status in (
            'active', 'trialing', 'past_due'
          )
          and (
            v_profile.usage_units_total is null
            or v_profile.usage_week_units_total is null
          )
          then 'plan_limits_unconfigured'
        when coalesce(v_five_remaining, 0) < p_reserved_credits
          then 'five_hour_allowance_exhausted'
        when coalesce(v_week_remaining, 0) < p_reserved_credits
          then 'weekly_allowance_exhausted'
        else 'insufficient_topup_credits'
      end,
      'five_hour_remaining', v_five_remaining,
      'five_hour_reset_at', v_profile.usage_window_ends_at,
      'weekly_remaining', v_week_remaining,
      'weekly_reset_at', v_profile.usage_week_ends_at,
      'topup_credits_balance', v_profile.topup_credits_balance
    );
  end if;

  insert into public.zuvyr_usage_records (
    user_id,
    request_id,
    idempotency_key,
    capability,
    provider,
    model_tool,
    pricing_version,
    funding_source,
    reserved_credits,
    estimated_provider_cost_microusd,
    five_hour_started_at,
    five_hour_ends_at,
    weekly_started_at,
    weekly_ends_at
  )
  values (
    p_user_id,
    trim(p_request_id),
    trim(p_idempotency_key),
    trim(p_capability),
    trim(p_provider),
    trim(p_model_tool),
    trim(p_pricing_version),
    v_funding_source,
    p_reserved_credits,
    p_estimated_provider_cost_microusd,
    v_profile.usage_window_started_at,
    v_profile.usage_window_ends_at,
    v_profile.usage_week_started_at,
    v_profile.usage_week_ends_at
  )
  returning * into v_existing;

  return jsonb_build_object(
    'success', true,
    'replayed', false,
    'usage_record_id', v_existing.id,
    'funding_source', v_existing.funding_source,
    'reserved_credits', v_existing.reserved_credits,
    'five_hour_reset_at', v_existing.five_hour_ends_at,
    'weekly_reset_at', v_existing.weekly_ends_at,
    'topup_credits_balance', case
      when v_funding_source = 'topup'
        then v_profile.topup_credits_balance - p_reserved_credits
      else v_profile.topup_credits_balance
    end
  );
end;
$function$;

create or replace function public.settle_zuvyr_usage(
  p_request_id text,
  p_actual_credits integer,
  p_actual_provider_cost_microusd numeric,
  p_revenue_microusd numeric,
  p_gross_profit_microusd numeric,
  p_gross_margin_bps integer,
  p_provider_usage jsonb,
  p_enforcement_enabled boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_record public.zuvyr_usage_records%rowtype;
  v_refund integer;
begin
  if not coalesce(p_enforcement_enabled, false) then
    return jsonb_build_object(
      'success', false,
      'error', 'usage_enforcement_disabled'
    );
  end if;

  if p_actual_credits is null
    or p_actual_credits < 0
    or p_actual_provider_cost_microusd is null
    or p_actual_provider_cost_microusd < 0
    or p_revenue_microusd is null
    or p_revenue_microusd < 0
    or p_gross_profit_microusd is null
    or p_gross_margin_bps is null
  then
    return jsonb_build_object(
      'success', false,
      'error', 'invalid_usage_settlement'
    );
  end if;

  select *
  into v_record
  from public.zuvyr_usage_records
  where request_id = trim(p_request_id)
  for update;

  if not found then
    return jsonb_build_object(
      'success', false,
      'error', 'usage_reservation_not_found'
    );
  end if;

  if v_record.state in ('settled', 'refunded') then
    return jsonb_build_object(
      'success', true,
      'replayed', true,
      'state', v_record.state,
      'actual_credits', v_record.actual_credits,
      'refunded_credits', v_record.refunded_credits
    );
  end if;

  if p_actual_credits > v_record.reserved_credits then
    return jsonb_build_object(
      'success', false,
      'error', 'actual_usage_exceeds_reservation'
    );
  end if;

  v_refund := v_record.reserved_credits - p_actual_credits;

  perform id
  from public.profiles
  where id = v_record.user_id
  for update;

  if not found then
    return jsonb_build_object(
      'success', false,
      'error', 'user_not_found'
    );
  end if;

  if v_refund > 0 and v_record.funding_source = 'subscription' then
    update public.profiles
    set
      usage_units_used = greatest(0, usage_units_used - v_refund),
      usage_week_units_used = greatest(
        0,
        usage_week_units_used - v_refund
      ),
      billing_updated_at = now()
    where id = v_record.user_id;
  elsif v_refund > 0 and v_record.funding_source = 'topup' then
    update public.profiles
    set
      topup_credits_balance = topup_credits_balance + v_refund,
      billing_updated_at = now()
    where id = v_record.user_id;
  end if;

  update public.zuvyr_usage_records
  set
    actual_credits = p_actual_credits,
    refunded_credits = v_refund,
    actual_provider_cost_microusd =
      p_actual_provider_cost_microusd,
    revenue_microusd = p_revenue_microusd,
    gross_profit_microusd = p_gross_profit_microusd,
    gross_margin_bps = p_gross_margin_bps,
    provider_usage = coalesce(p_provider_usage, '{}'::jsonb),
    state = case
      when p_actual_credits = 0 then 'refunded'
      else 'settled'
    end,
    settled_at = now(),
    updated_at = now()
  where id = v_record.id;

  return jsonb_build_object(
    'success', true,
    'replayed', false,
    'state', case
      when p_actual_credits = 0 then 'refunded'
      else 'settled'
    end,
    'reserved_credits', v_record.reserved_credits,
    'actual_credits', p_actual_credits,
    'refunded_credits', v_refund
  );
end;
$function$;

create or replace function public.refund_zuvyr_usage(
  p_request_id text,
  p_actual_provider_cost_microusd numeric default 0,
  p_enforcement_enabled boolean default false
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
begin
  return public.settle_zuvyr_usage(
    p_request_id,
    0,
    p_actual_provider_cost_microusd,
    0,
    -p_actual_provider_cost_microusd,
    0,
    jsonb_build_object('refund', true),
    p_enforcement_enabled
  );
end;
$function$;

revoke execute on function public.reserve_zuvyr_usage(
  uuid,
  text,
  text,
  text,
  text,
  text,
  text,
  integer,
  numeric,
  boolean,
  boolean
)
from public, anon, authenticated;

grant execute on function public.reserve_zuvyr_usage(
  uuid,
  text,
  text,
  text,
  text,
  text,
  text,
  integer,
  numeric,
  boolean,
  boolean
)
to service_role;

revoke execute on function public.settle_zuvyr_usage(
  text,
  integer,
  numeric,
  numeric,
  numeric,
  integer,
  jsonb,
  boolean
)
from public, anon, authenticated;

grant execute on function public.settle_zuvyr_usage(
  text,
  integer,
  numeric,
  numeric,
  numeric,
  integer,
  jsonb,
  boolean
)
to service_role;

revoke execute on function public.refund_zuvyr_usage(
  text,
  numeric,
  boolean
)
from public, anon, authenticated;

grant execute on function public.refund_zuvyr_usage(
  text,
  numeric,
  boolean
)
to service_role;

commit;
