-- ZUVYR V1 Pack 02: Intelligence Core task persistence foundation.
-- Additive only. No task is created or executed by this migration.
-- Runtime orchestration remains disabled unless explicitly enabled.

create table if not exists public.zuvyr_task_runs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete restrict,
  idempotency_key text not null,
  plan_version text not null,
  intent text not null,
  state text not null default 'pending',
  plan jsonb not null,
  final_result jsonb,
  error_code text,
  cancel_requested boolean not null default false,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint zuvyr_task_runs_idempotency_unique unique (user_id, idempotency_key),
  constraint zuvyr_task_runs_state_allowed
    check (state in ('pending', 'running', 'succeeded', 'failed', 'cancelled')),
  constraint zuvyr_task_runs_idempotency_valid
    check (length(trim(idempotency_key)) between 8 and 128),
  constraint zuvyr_task_runs_intent_valid
    check (length(trim(intent)) between 1 and 500)
);

create table if not exists public.zuvyr_task_steps (
  id bigint generated by default as identity primary key,
  task_run_id uuid not null references public.zuvyr_task_runs(id) on delete cascade,
  step_key text not null,
  capability text not null,
  sequence_number integer not null,
  state text not null default 'pending',
  attempts integer not null default 0,
  max_attempts integer not null,
  depends_on jsonb not null default '[]'::jsonb,
  input jsonb,
  output jsonb,
  provider text,
  model_tool text,
  usage_record_id bigint references public.zuvyr_usage_records(id) on delete restrict,
  error_code text,
  started_at timestamptz,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  constraint zuvyr_task_steps_run_key_unique unique (task_run_id, step_key),
  constraint zuvyr_task_steps_run_sequence_unique unique (task_run_id, sequence_number),
  constraint zuvyr_task_steps_state_allowed
    check (state in ('pending', 'running', 'succeeded', 'failed', 'cancelled')),
  constraint zuvyr_task_steps_attempts_valid
    check (attempts >= 0 and max_attempts between 1 and 3 and attempts <= max_attempts),
  constraint zuvyr_task_steps_sequence_valid check (sequence_number >= 0),
  constraint zuvyr_task_steps_dependencies_array check (jsonb_typeof(depends_on) = 'array')
);

create index if not exists zuvyr_task_runs_user_created_idx
  on public.zuvyr_task_runs (user_id, created_at desc);

create index if not exists zuvyr_task_runs_state_updated_idx
  on public.zuvyr_task_runs (state, updated_at);

create index if not exists zuvyr_task_steps_run_state_idx
  on public.zuvyr_task_steps (task_run_id, state, sequence_number);

alter table public.zuvyr_task_runs enable row level security;
alter table public.zuvyr_task_steps enable row level security;

revoke all on table public.zuvyr_task_runs from public, anon, authenticated;
revoke all on table public.zuvyr_task_steps from public, anon, authenticated;

grant select, insert, update on table public.zuvyr_task_runs to service_role;
grant select, insert, update on table public.zuvyr_task_steps to service_role;
grant usage, select on sequence public.zuvyr_task_steps_id_seq to service_role;

comment on table public.zuvyr_task_runs is
  'Pack 02 service-role-only orchestration runs; runtime activation is separate.';

comment on table public.zuvyr_task_steps is
  'Pack 02 ordered task steps with retries, dependencies and usage-ledger linkage.';
